---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name:  east-sriov-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/intelnic_east
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "ipam": {
    "type": "host-local",
    "subnet": "10.20.30.0/25",
    "gateway": "10.20.10.1"
  }
}'

