apiVersion: v1
kind: Pod
metadata:
  name: bar-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: east-sriov-net
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        openshift.io/intelnic_east: '1'
      limits:
        openshift.io/intelnic_east: '1'

